# UNDERSTANDING NEED DROPOUT LAYER

**Importing Liberaries**

In [68]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
import warnings
from sklearn.model_selection import train_test_split
warnings.filterwarnings("ignore", category=FutureWarning)
import tensorflow as tf 
from tensorflow import keras 
from sklearn.metrics import classification_report, confusion_matrix

In [69]:
data = pd.read_csv("S:/Github/DATASET/sonar_dataset.csv" , header=None)
data.head(4)

0       1       2       3       4       5       6       7       8   \
0  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   

       9   ...      51      52      53      54      55      56      57  \
0  0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084   
1  0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
2  0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
3  0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   

       58      59  60  
0  0.0090  0.0032   R  
1  0.0052  0.0044   R  
2  0.0095  0.0078   R  
3  0.0040  0.0117   R  

[4 rows x 61 columns]

**Creating Train and Test Data**

In [70]:
x = data.drop(columns = 60)
y = data[60]

y = y.replace({"R" :0 , "M" : 1})
y.value_counts()

60
1    111
0     97
Name: count, dtype: int64

In [71]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=5)
x_train.shape, x_test.shape, y_train.shape, y_test.shape


((166, 60), (42, 60), (166,), (42,))

**Creating Model Without dropout layer**

In [72]:
model = keras.Sequential(
    [
        keras.layers.Dense(60 , input_shape=(60,) , activation = "relu"),
        keras.layers.Dense(30 , activation = "relu"),
        keras.layers.Dense(15 , activation = "relu"),
        keras.layers.Dense(1 , activation = "sigmoid"),
    ]
)

model.compile( 
    optimizer = "adam" ,
    loss = "binary_crossentropy", 
    metrics = ['accuracy']
)

history = model.fit(x_train , y_train , epochs = 80 , validation_split = 0.2 , batch_size = 8
)

Epoch 1/80


c:\Users\13zer\anaconda3\envs\dl\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


17/17 ━━━━━━━━━━━━━━━━━━━━ 3s 24ms/step - accuracy: 0.5821 - loss: 0.6858 - val_accuracy: 0.6176 - val_loss: 0.6826
Epoch 2/80
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7614 - loss: 0.6718 - val_accuracy: 0.6176 - val_loss: 0.6774
Epoch 3/80
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6935 - loss: 0.6640 - val_accuracy: 0.6471 - val_loss: 0.6615
Epoch 4/80
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6867 - loss: 0.6505 - val_accuracy: 0.5882 - val_loss: 0.6659
Epoch 5/80
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7741 - loss: 0.6021 - val_accuracy: 0.6176 - val_loss: 0.6315
Epoch 6/80
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7246 - loss: 0.5857 - val_accuracy: 0.6176 - val_loss: 0.6230
Epoch 7/80
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7606 - loss: 0.5648 - val_accuracy: 0.6471 - val_loss: 0.5951
Epoch 8/80
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8008 - loss: 0.5172 - val_accuracy: 0.7353 - val_loss: 0.56

**Model evaluation and Metrics**

In [73]:
model.evaluate(x_test , y_test)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.8105 - loss: 0.7905


[0.8154451251029968, 0.8095238208770752]

In [74]:
y_predicted = np.round(model.predict(x_test)).reshape(-1)
y_predicted

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step


array([1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1.,
       1., 1., 1., 1., 0., 0., 1., 1., 1., 0., 1., 0., 1., 1., 1., 0., 1.,
       0., 0., 1., 1., 0., 0., 0., 0.], dtype=float32)

In [ ]:
print(f" Confusion matrix  without Dropout Layer: \n {confusion_matrix(y_test , y_predicted).reshape(2,2)}")


 Confusion matrix : 
 [[13  2]
 [ 6 21]]


In [ ]:
print(f"classification report without Dropout Layer: \n {classification_report(y_test , y_predicted)}")

classification report : 
               precision    recall  f1-score   support

           0       0.68      0.87      0.76        15
           1       0.91      0.78      0.84        27

    accuracy                           0.81        42
   macro avg       0.80      0.82      0.80        42
weighted avg       0.83      0.81      0.81        42



**Creating Model With Dropout Layers**

In [77]:
model1= keras.Sequential(
    [
        keras.layers.Dense(100 , input_shape=(60,) , activation = "relu"),
        keras.layers.Dropout(0.5),
        keras.layers.Dense(40 , activation = "relu"),
        keras.layers.Dropout(0.5),
        keras.layers.Dense(25 , activation = "relu"),
        keras.layers.Dropout(0.5),
        keras.layers.Dense(1 , activation = "sigmoid"),
    ]
)

model1.compile( 
    optimizer = "adam" ,
    loss = "binary_crossentropy", 
    metrics = ['accuracy']
)

history = model1.fit(x_train , y_train , epochs = 100 , validation_split = 0.2 , batch_size = 8
)


c:\Users\13zer\anaconda3\envs\dl\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - accuracy: 0.5280 - loss: 0.7287 - val_accuracy: 0.5294 - val_loss: 0.6912
Epoch 2/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4267 - loss: 0.7230 - val_accuracy: 0.5294 - val_loss: 0.6921
Epoch 3/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5300 - loss: 0.6981 - val_accuracy: 0.6471 - val_loss: 0.6857
Epoch 4/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5963 - loss: 0.7152 - val_accuracy: 0.5588 - val_loss: 0.6874
Epoch 5/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5748 - loss: 0.6650 - val_accuracy: 0.5294 - val_loss: 0.6862
Epoch 6/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.4453 - loss: 0.7110 - val_accuracy: 0.6176 - val_loss: 0.6875
Epoch 7/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6414 - loss: 0.6530 - val_accuracy: 0.6176 - val_loss: 0.6866
Epoch 8/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4559 - loss: 0.7171 - val_accuracy: 0.500

**Model evaluation and Metrics**

In [78]:
model1.evaluate(x_test , y_test)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.8631 - loss: 0.3128


[0.3324354887008667, 0.8571428656578064]

In [79]:
y_predicted_1 = np.round(model1.predict(x_test)).reshape(-1)

1/2 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/stepWARNING:tensorflow:6 out of the last 8 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x000001D49EDA7420> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step


In [ ]:
print(f" Confusion matrix with Dropout Layer: \n {confusion_matrix(y_test , y_predicted_1).reshape(2,2)}")

 Confusion matrix : 
 [[14  1]
 [ 5 22]]


In [ ]:
print(f"classification report with Dropout Layer: \n {classification_report(y_test , y_predicted_1)}")

classification report : 
               precision    recall  f1-score   support

           0       0.74      0.93      0.82        15
           1       0.96      0.81      0.88        27

    accuracy                           0.86        42
   macro avg       0.85      0.87      0.85        42
weighted avg       0.88      0.86      0.86        42



*as we can see there is a significant increase in all metrics of Classification report for Model1*