BERT ( bidirectional encoder representaion from transformers ) :   
allow to generate contexual embeddings 

In [2]:
import tensorflow_hub as hub
import tensorflow_text as text

2025-05-25 11:25:51.411408: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-05-25 11:25:51.492215: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-05-25 11:25:51.570985: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1748152551.638697    4277 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1748152551.657737    4277 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1748152551.800515    4277 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linkin

In [3]:
preprocess_url = "https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3"
encoder_url = "https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4"

In [4]:
bert_preprocess = hub.KerasLayer(preprocess_url)
text_test = ['nice movie indeed' ,'i love python programming']
text_process = bert_preprocess(text_test)
text_process.keys()

2025-05-25 11:25:58.562700: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


dict_keys(['input_type_ids', 'input_mask', 'input_word_ids'])

In [5]:
text_process['input_mask']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)>

In [7]:
bert_model = hub.KerasLayer(encoder_url)

result = bert_model(text_process)
result.keys()

2025-05-25 11:31:15.861778: W external/local_xla/xla/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 93763584 exceeds 10% of free system memory.


dict_keys(['pooled_output', 'sequence_output', 'encoder_outputs', 'default'])

In [8]:
result['encoder_outputs']

[<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
 array([[[ 0.12901431,  0.0064473 , -0.03614966, ...,  0.04999612,
           0.06149197, -0.0265754 ],
         [ 1.1753383 ,  1.2140788 ,  1.1569982 , ...,  0.1163439 ,
          -0.35855347, -0.40490162],
         [ 0.03859065,  0.5386996 , -0.21089783, ...,  0.21858186,
           0.72601694, -1.1158606 ],
         ...,
         [-0.07587012, -0.2542191 ,  0.7075511 , ...,  0.5054202 ,
          -0.18878667,  0.15028363],
         [-0.16066603, -0.2808969 ,  0.57597065, ...,  0.5275854 ,
          -0.11141386,  0.0288756 ],
         [-0.04428149, -0.2027958 ,  0.5909356 , ...,  0.8133834 ,
          -0.390758  , -0.0260174 ]],
 
        [[ 0.18903595,  0.02752538, -0.06513737, ..., -0.00620209,
           0.15053889,  0.03165443],
         [ 0.5916147 ,  0.7589137 , -0.07240663, ...,  0.6190398 ,
           0.8292889 ,  0.16161954],
         [ 1.4460826 ,  0.4460265 ,  0.4099028 , ...,  0.48255897,
           0.6269116 ,  0.13