# **Descriptive Statastics In Numpy**

In [94]:
import numpy as np 

**Mean**

In [95]:
arr = np.array(
    [
        [1, 2, 3 ,343,32 ],  
        [4, 5, 6,32,2],
        [7, 8, 9, 0, 0],
        [10, 11, 12, 0, 0],
    ]
)

arr.shape

print(np.mean(arr, axis=0)) # mean of each column

# column wise mean of first 2 rows for first 3 columns 
print(np.mean(arr[0:2 , :3] , axis = 0)) 

 # rowwise mean of first 3 columns till 4 columns
print(np.mean(arr[0:3  , :4] , axis = 1))

[ 5.5   6.5   7.5  93.75  8.5 ]
[2.5 3.5 4.5]
[87.25 11.75  6.  ]


**Median**

In [96]:
print(np.median(arr[: , : ] , axis = 0 ))  # columnwise median of all rows
print(np.median(arr[: , : ] , axis = 1 )) # rowwise median of all rows

[ 5.5  6.5  7.5 16.   1. ]
[ 3.  5.  7. 10.]


**Correlation matrix**

In [97]:
print(np.corrcoef(arr))
print(np.corrcoef(arr[ 0:3 ,0:2])) 
print(np.corrcoef(arr[:,0] , arr[ :,3]))

[[ 1.          0.98046537 -0.66923283 -0.67347626]
 [ 0.98046537  1.         -0.51016752 -0.51571805]
 [-0.66923283 -0.51016752  1.          0.99906848]
 [-0.67347626 -0.51571805  0.99906848  1.        ]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[ 1.         -0.82094411]
 [-0.82094411  1.        ]]


**Standard Deviation**

In [98]:
print(np.std(arr))
print(np.std(arr[: , 1])) # standard deviation of second column 
print(np.std(arr[: , :3]))

73.65207057510331
3.3541019662496847
3.452052529534663


**Adding arrays**

In [99]:
arr1 = np.array(
   [ [13,14,15] ,
    [18,19,20] ,
    [21,22,23] ,
    [24,25,26] ,]
)

# for addition both array must hame same dimensions

arr_total = arr[:4 ,:3] + arr1
arr_total

array([[14, 16, 18],
       [22, 24, 26],
       [28, 30, 32],
       [34, 36, 38]])

**Multiplying arrays**

In [100]:
# no of columns of first array must be equal to the no of rows of second array

arr_product = arr[:4 , :3] * arr1
arr_product1 = arr[:3 , :4].T * arr1
arr_product2 = arr[1,:3] * arr1


print(arr_product)
print(arr_product1)
print(arr_product2)


[[ 13  28  45]
 [ 72  95 120]
 [147 176 207]
 [240 275 312]]
[[  13   56  105]
 [  36   95  160]
 [  63  132  207]
 [8232  800    0]]
[[ 52  70  90]
 [ 72  95 120]
 [ 84 110 138]
 [ 96 125 156]]


**Concatenation Of Array**

In [101]:
a= np.array([1,2,3,4,5])
b= np.array([6,7,8,9,10])

print(np.vstack([a,b])) 
print(np.vstack([b,b]))
print(np.hstack([a,b]))
print(np.hstack([a,a]))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 6  7  8  9 10]
 [ 6  7  8  9 10]]
[ 1  2  3  4  5  6  7  8  9 10]
[1 2 3 4 5 1 2 3 4 5]


**Some basic functions**

In [102]:
print(a.min()) # min value in array a 
print(b.max()) # max value in array a 
print(np.vstack([a,b]).min())

# variance  in array horizontal stack of a and b
print(np.hstack([a,b]).var()) 
print(b.var())



1
10
1
8.25
2.0


**Ravel function**

In [103]:
# Used to flatten the array
print(np.vstack([a,b]).ravel()) 

[ 1  2  3  4  5  6  7  8  9 10]
